# Generated by Django 3.0 on 2020-01-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(help_text='abstract number related with currency to represent currency value and achieve exchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money_jars.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount_before', models.FloatField()),
                ('amount_after', models.FloatField()),
                ('amount_operation', models.FloatField()),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money_jars.Jar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money_jars.Currency')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit', to='money_jars.Operation')),
                ('withdraw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdraw', to='money_jars.Operation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
